### PR TITLE
docs: Setup Read the Docs

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by mrogowski** [comment]
This happens occasionally... I'm not sure if this is the usual runners unreliability, or perhaps there is something going on in our code. I just noticed a few days ago that typically this happens before tests hang:

```
testPtrArray (test_ptr.TestPtr.testPtrArray) ... testPtrArray (test_ptr.TestPtr.testPtrArray) ... FAIL
testPtrMemory (test_ptr.TestPtr.testPtrMemory) ... FAIL
testPtrMemory (test_ptr.TestPtr.testPtrMemory) ... FAIL
testAddrAccesibleCData (test_query.TestQuery.testAddrAccesibleCData) ... FAIL
```

**Comment by dalcinl** [comment]
I'll take a look at the tests. Perhaps it is an issue in our side.

I'm merging this PR. Please rebase your doc PR, then RTD will build the PR on every push.

**Comment by mrogowski** [comment]
I reran some tests locally with the same container and was not able to reproduce any issues in 10,000+ repetitions of the test.

Docs are live: https://shmem4py--5.org.readthedocs.build/en/5/

**Comment by mrogowski** [comment]
Update: I was able to reproduce the error with `oshmem_fedora`.

**Pull request merged**
